[profile.default]
src = "src"
out = "out"
test = "test"
solc_version = "0.8.33"
optimizer = true
optimizer_runs = 200
ffi = true
verbosity = 2
via_ir = true

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }
gas_reports = ["*"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
