name: Smart Contract CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Cache Foundry
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry
            lib
          key: ${{ runner.os }}-foundry-${{ hashFiles('**/foundry.toml') }}

      - name: Format check (non-blocking)
        run: forge fmt --check || echo "⚠️ Formatting issues found. Run 'forge fmt' locally."
      - name: Install dependencies
        run: forge install
      - name: Build
        run: forge build --sizes

      - name: Test
        run: forge test -vvv

      - name: Gas snapshot
        run: forge snapshot
